<?php return array (
  'october\\demo\\Plugin' => 'plugins\\october\\demo\\Plugin.php',
  'backend\\Controllers\\index' => 'modules\\backend\\controllers\\index.php',
  'backend\\Controllers\\auth' => 'modules\\backend\\controllers\\auth.php',
  'backend\\Controllers\\users' => 'modules\\backend\\controllers\\users.php',
  'backend\\Controllers\\preferences' => 'modules\\backend\\controllers\\preferences.php',
  'system\\Controllers\\settings' => 'modules\\system\\controllers\\settings.php',
  'cms\\Controllers\\themes' => 'modules\\cms\\controllers\\themes.php',
  'system\\Controllers\\updates' => 'modules\\system\\controllers\\updates.php',
  'fw\\editme\\Plugin' => 'plugins\\fw\\editme\\Plugin.php',
  'rainlab\\builder\\Plugin' => 'plugins\\rainlab\\builder\\Plugin.php',
  'rainlab\\translate\\Plugin' => 'plugins\\rainlab\\translate\\Plugin.php',
  'romanov\\clearcachewidget\\Plugin' => 'plugins\\romanov\\clearcachewidget\\Plugin.php',
  'samuell\\contenteditor\\Plugin' => 'plugins\\samuell\\contenteditor\\Plugin.php',
  'zen\\robots\\Plugin' => 'plugins\\zen\\robots\\Plugin.php',
  'Fw\\EditMe\\Models\\Settings' => 'plugins\\fw\\editme\\models\\Settings.php',
  'RainLab\\Translate\\Classes\\Translator' => 'plugins\\rainlab\\translate\\classes\\Translator.php',
  'RainLab\\Translate\\Classes\\LocaleMiddleware' => 'plugins\\rainlab\\translate\\classes\\LocaleMiddleware.php',
  'RainLab\\Translate\\Models\\Locale' => 'plugins\\rainlab\\translate\\models\\Locale.php',
  'RainLab\\Translate\\Behaviors\\TranslatablePageUrl' => 'plugins\\rainlab\\translate\\behaviors\\TranslatablePageUrl.php',
  'RainLab\\Translate\\Classes\\TranslatableBehavior' => 'plugins\\rainlab\\translate\\classes\\TranslatableBehavior.php',
  'RainLab\\Translate\\Behaviors\\TranslatablePage' => 'plugins\\rainlab\\translate\\behaviors\\TranslatablePage.php',
  'Samuell\\ContentEditor\\Components\\ContentEditor' => 'plugins\\samuell\\contenteditor\\components\\ContentEditor.php',
  'RainLab\\Translate\\Classes\\EventRegistry' => 'plugins\\rainlab\\translate\\classes\\EventRegistry.php',
  'RainLab\\Translate\\Models\\Message' => 'plugins\\rainlab\\translate\\models\\Message.php',
  'Samuell\\ContentEditor\\Models\\Settings' => 'plugins\\samuell\\contenteditor\\models\\Settings.php',
  'Samuell\\ContentEditor\\Http\\Controllers\\AdditionalStylesController' => 'plugins\\samuell\\contenteditor\\http\\controllers\\AdditionalStylesController.php',
);