tabs:
    stretch: true
    defaultTab: Контакты
    icons:
        Контакты: icon-address-book-o
        Соц. Сети: icon-comments
        Контент: icon-pencil
        Главная: icon-bookmark-o
        О проекте: icon-info
        Вопрос-ответ: icon-question-circle

    fields:
        header_phone:
            label: Телефон в меню
            default: +7 (495) 123 45 56
            tab: Контакты
        phone:
            label: Телефон в подвале и боковом меню
            default: +7 (495) 123 45 56
            tab: Контакты
        email:
            label: E-mail
            default: hello@world.com
            tab: Контакты
        tg_link:
            label: Telegram
            default: /
            tab: Контакты
        wapp_link:
            label: WhatsApp
            default: /
            tab: Контакты
        soc_links:
          type: repeater
          label: Ссылки на соц. сети
          titleFrom: link_name
          tab: Соц. Сети
          form:
            fields:
              link_name:
                label: Название ссылки
              link:
                label: Ссылка
        side_soc_links:
          type: repeater
          label: Боковые ссылки на соц. сети
          titleFrom: link_name
          tab: Соц. Сети
          form:
            fields:
              link_name:
                label: Название ссылки
              link:
                label: Ссылка
        work_examples:
          type: repeater
          label: Примеры работ
          titleFrom: name
          tab: Контент
          form:
            fields:
              name:
                label: Название
              type:
                label: Жанр
              example:
                type: mediafinder
        audience_stages:
          type: repeater
          label: Для кого этот курс
          comment: Краткое описание аудитории
          titleFrom: about
          tab: Контент
          form:
            fields:
              about:
                label: Описание
                type: textarea
                size: small
        project_authors:
          type: repeater
          label: Авторы курсов
          titleFrom: name
          tab: Контент
          form:
            fields:
              name:
                label: Имя и фамилия автора
              about:
                label: Описание
              image:
                type: mediafinder
        content_creative_result1:
            label: Творческий результат 1
            default: Проведете время креативно и необычно 1
            tab: Контент
        content_creative_result2:
            label: Творческий результат 2
            default: Проведете время креативно и необычно 2
            tab: Контент
        content_creative_result3:
            label: Творческий результат 3
            default: Проведете время креативно и необычно 3
            tab: Контент
        content_creative_result4:
            label: Творческий результат 4
            default: Проведете время креативно и необычно 4
            tab: Контент
        content_creative_result5:
            label: Творческий результат 5
            default: Проведете время креативно и необычно 5
            tab: Контент
        content_creative_result6:
            label: Творческий результат 6
            default: Проведете время креативно и необычно 6
            tab: Контент
        home_main_title:
            label: Начало заголовка
            default: Творческий результат
            tab: Главная
        home_main_title_add:
          type: repeater
          label: Продолжение заголовка
          titleFrom: text
          tab: Главная
          form:
            fields:
              text:
                label: Текст
              color:
                label: Цвет текста
                type: colorpicker
        home_video_link1:
            label: Ссылка для видео 1
            tab: Главная
        home_video_label1:
            label: Подпись к видео 1
            default: Видео о нашем проекте
            tab: Главная
        home_video_type1:
            label: Видео хостинг для видео 1
            type: radio
            default: youtube
            options:
                youtube: YouTube
                vimeo: Vimeo
        home_video_link2:
            label: Ссылка для видео 2
            tab: Главная
        home_video_label2:
            label: Подпись к видео 2
            default: Видео о нашем проекте
            tab: Главная
        home_video_type2:
            label: Видео хостинг для видео 2
            type: radio
            default: youtube
            options:
                youtube: YouTube
                vimeo: Vimeo
        about_statistics_blocks:
          type: repeater
          label: Блоки статистики
          titleFrom: text
          tab: О проекте
          form:
            fields:
              value:
                label: Значение
              text:
                label: Подпись
        our_worths:
          type: repeater
          label: Наши ценности
          titleFrom: about
          tab: О проекте
          form:
            fields:
              about:
                label: Описание
                type: textarea
                size: small
        algorithm_stages:
          type: repeater
          label: Как проходит обучение
          comment: Этапы обучения
          titleFrom: about
          tab: О проекте
          form:
            fields:
              about:
                label: Описание
                type: textarea
                size: small
        about_video_link1:
            label: Ссылка для видео 1
            tab: О проекте
        about_video_label1:
            label: Подпись к видео 1
            default: Видео о нашем проекте
            tab: О проекте
        about_video_type1:
            label: Видео хостинг для видео 1
            type: radio
            default: youtube
            options:
                youtube: YouTube
                vimeo: Vimeo
        about_video_link2:
            label: Ссылка для видео 2
            tab: О проекте
        about_video_label2:
            label: Подпись к видео 2
            default: Видео о нашем проекте
            tab: О проекте
        about_video_type2:
            label: Видео хостинг для видео 2
            type: radio
            default: youtube
            options:
                youtube: YouTube
                vimeo: Vimeo
        faqs:
          type: repeater
          label: Вопрос-ответ
          titleFrom: question
          tab: Вопрос-ответ
          form:
            fields:
              question:
                label: Вопрос
                type: textarea
                size: small
              answer:
                label: Ответ
                type: richeditor
                size: large
              mini:
                label: Показывать на главной
                type: switch
                comment: Показывать на главной странице в блоке "Вопрос - ответ"