tabs:
    stretch: true
    defaultTab: Контакты
    icons:
        Контакты: icon-address-book-o
        Соц. Сети: icon-comments
        Контент: icon-pencil
        Вопрос-ответ: icon-question-circle

    fields:
        phone:
            label: Телефон
            default: +7 (495) 123 45 56
            tab: Контакты
        email:
            label: E-mail
            default: hello@world.com
            tab: Контакты
        tg_link:
            label: Telegram
            default: /
            tab: Контакты
        wapp_link:
            label: WhatsApp
            default: /
            tab: Контакты
        soc_links:
          type: repeater
          label: Ссылки на соц. сети
          titleFrom: link_name
          tab: Соц. Сети
          form:
            fields:
              link_name:
                label: Название ссылки
              link:
                label: Ссылка
        side_soc_links:
          type: repeater
          label: Боковые ссылки на соц. сети
          titleFrom: link_name
          tab: Соц. Сети
          form:
            fields:
              link_name:
                label: Название ссылки
              link:
                label: Ссылка
        work_examples:
          type: repeater
          label: Примеры работ
          titleFrom: name
          tab: Контент
          form:
            fields:
              name:
                label: Название
              type:
                label: Жанр
        algorithm_stages:
          type: repeater
          label: Как проходит обучение
          comment: Этапы обучения
          titleFrom: about
          tab: Контент
          form:
            fields:
              about:
                label: Описание
                type: textarea
                size: small
        our_worths:
          type: repeater
          label: Наши ценности
          titleFrom: about
          tab: Контент
          form:
            fields:
              about:
                label: Описание
                type: textarea
                size: small
        faqs:
          type: repeater
          label: Вопрос-ответ
          titleFrom: question
          tab: Вопрос-ответ
          form:
            fields:
              question:
                label: Вопрос
                type: textarea
                size: small
              answer:
                label: Ответ
                type: textarea
                size: large
              mini:
                label: Показывать на главной
                type: switch
                comment: Показывать на главной странице в блоке "Вопрос - ответ"